%% @config(../mindmap-config.json)
mindmap
    Directeur
        Ce qu'il fait
            Utilise une application pour ajouter les nouvelles
        Ce qu'il dit
            Il veut suivre les absences par tous les établissements