@startuml uses_cases_pkg_GestionPriseDeService
left to right direction

actor Directeur as directeur
actor ResponsableFormation as responsableFormation

package Gestion_PriseDeService {

  directeur -- (Gestion personnel)
  (Gestion personnel) <.. (imprimer attestation de travail) : extend

  responsableFormation -- (Consultez personnel)
  (Consultez personnel) <.. (imprimer attestation de travail) : extend

  directeur -- (Gestion categories)
  responsableFormation -- (Consultez categories)

}

@enduml