%% @config(../mindmap-config.json)
mindmap
    pkg_PriseDeServices Responsable
        Ce qu'il fait
            Utilisez les applications Microsoft pour gérer et imprimer les attestations du personnel.
        Ce qu'il dit
            Il consulte les informations du personnel et imprime des attestations de travail.