%% @config(../mindmap-config.json)
mindmap
    pkg_PriseDeSeervices Directeur
        Ce qu'il fait
            Utilise une application pour gérer le personnel et les catégories.
        Ce qu'il dit
            Il gère les employés, imprime leurs attestations de travail et gère les catégories de chaque personnel.