%% @config(../mindmap-config.json)
mindmap
    Directeur
        Ce qu'il fait
            Utilise une application pour gérer le personnel et les catégories.
        Ce qu'il dit
            Il veut suivre le travail, les missions et les catégories du personnel.