%% @config(../mindmap-config.json)
mindmap
    Responsable
        Ce qu'il fait
            Utilisez les applications Microsoft pour gérer et imprimer les attestations du personnel.
        Ce qu'il dit
            Il veut suivre le travail et les missions du personnel.