<?php

namespace Database\Seeders\GestionPersonnels;

use App\Models\GestionPersonnels\Ville;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VilleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $villeData = [
            ['nom' => 'Tetouan'],
            ['nom' => 'Tanger'],
            ['nom' => 'Chefchaouen'],
            ['nom' => 'Fès'],
            ['nom' => 'Meknès'],
            ['nom' => 'Rabat'],
            ['nom' => 'Casablanca'],
            ['nom' => 'Marrakech'],
            ['nom' => 'Agadir'],
            ['nom' => 'Essaouira'],
            ['nom' => 'Ouarzazate'],
            ['nom' => 'Errachidia'],
            ['nom' => 'Oujda'],
            ['nom' => 'Nador'],
            ['nom' => 'El Jadida'],
            ['nom' => 'Safi'],
            ['nom' => 'Kenitra'],
            ['nom' => 'Mohammedia'],
            ['nom' => 'Taza'],
            ['nom' => 'Beni Mellal'],
            ['nom' => 'Khouribga'],
            ['nom' => 'Settat'],
            ['nom' => 'Skhirat'],
            ['nom' => 'Tan-Tan'],
            ['nom' => 'Laâyoune'],
            ['nom' => 'Dakhla'],
            ['nom' => 'Tiznit'],
            ['nom' => 'Taroudant'],
            ['nom' => 'Al Hoceima'],
            ['nom' => 'Taourirt'],
            ['nom' => 'Tétouan'],
            ['nom' => 'Figuig'],
            ['nom' => 'Sefrou'],
            ['nom' => 'Tata'],
            ['nom' => 'Guelmim'],
            ['nom' => 'Taza'],
            ['nom' => 'Sidi Ifni'],
            ['nom' => 'Kénitra'],
            ['nom' => 'Sidi Bennour'],
            ['nom' => 'Larache'],
            ['nom' => 'Zagora'],
            ['nom' => 'Khemisset'],
            ['nom' => 'Azrou'],
            ['nom' => 'Ksar El Kebir'],
            ['nom' => 'Ksar El Kebir'],
            ['nom' => 'Oued Zem'],
            ['nom' => 'Midelt'],
            ['nom' => 'Berrechid'],
            ['nom' => 'Martil'],
            ['nom' => 'Fqih Ben Salah'],
            ['nom' => 'Oulad Teima'],
            ['nom' => 'Sidi Yahya El Gharb'],
            ['nom' => 'Sidi Slimane'],
            ['nom' => 'Souk Larbaa'],
            ['nom' => 'Tafraout'],
            ['nom' => 'Taliouine'],
            ['nom' => 'Youssoufia'],
            ['nom' => 'Sidi Kacem'],
            ['nom' => 'Skoura'],
            ['nom' => 'Zaio'],
            ['nom' => 'Sidi Bennour'],
            ['nom' => 'Sebta'],
            ['nom' => 'Oued Amlil'],
            ['nom' => 'Skhirate'],
            ['nom' => 'Berkane'],
            ['nom' => 'Taounate'],
            ['nom' => 'Sidi Smail'],
            ['nom' => 'Imzouren'],
            ['nom' => 'Ait Melloul'],
            ['nom' => 'Témara'],
            ['nom' => 'Ouarzazate Province'],
            ['nom' => 'Sidi Bennour Province'],
            ['nom' => 'Sidi Bennour Province'],
            ['nom' => 'Bouznika'],
            ['nom' => 'Ahfir'],
            ['nom' => 'Moulay Yacoub'],
            ['nom' => 'Fnideq'],
            ['nom' => 'Guisser'],
            ['nom' => 'Ouezzane'],
            ['nom' => 'Martil'],
            ['nom' => 'Ouazzane'],
            ['nom' => 'Ksar Sghir'],
            ['nom' => 'Tiznit Province'],
            ['nom' => 'El Aioun'],
            ['nom' => 'El Aioun'],
            ['nom' => 'Tahannaout'],
            ['nom' => 'Sidi Smail'],
            ['nom' => 'Sidi Yahya El Gharb'],
            ['nom' => 'Oulad Abbou'],
            ['nom' => 'Mechraa Bel Ksiri'],
            ['nom' => 'Guelmim Province'],
            ['nom' => 'Guelmim Province'],
            ['nom' => 'Benslimane'],
            ['nom' => 'Benslimane'],
            ['nom' => 'Benslimane'],
            ['nom' => 'Sidi Allal Tazi'],
            ['nom' => 'Midar'],
            ['nom' => 'Moulay Yacoub Province'],
            ['nom' => 'Moulay Yacoub Province'],
            ['nom' => 'Taroudant Province'],
            ['nom' => 'Taroudant Province'],
            ['nom' => 'Khemisset Province'],
            ['nom' => 'Khemisset Province'],
            ['nom' => 'Al Hoceima Province'],
            ['nom' => 'Al Hoceima Province'],
            ['nom' => 'Tiznit Province'],
            ['nom' => 'Tiznit Province'],
            ['nom' => 'Sidi Slimane Province'],
            ['nom' => 'Sidi Slimane Province'],
            ['nom' => 'Berkane Province'],
            ['nom' => 'Berkane Province'],
            ['nom' => 'Chtouka-Ait Baha'],
            ['nom' => 'Chtouka-Ait Baha'],
            ['nom' => 'Chtouka-Ait Baha'],
            ['nom' => 'Boujdour'],
            ['nom' => 'Boujdour'],
            ['nom' => 'Boujdour'],
            ['nom' => 'Kelaat Sraghna'],
            ['nom' => 'Kelaat Sraghna'],
            ['nom' => 'Kelaat Sraghna'],
            ['nom' => 'Moulay Abdallah'],
            ['nom' => 'Moulay Abdallah'],
            ['nom' => 'Moulay Abdallah'],
            ['nom' => 'Oued Ed-Dahab'],
            ['nom' => 'Oued Ed-Dahab'],
            ['nom' => 'Oued Ed-Dahab'],
            ['nom' => 'Tata Province'],
            ['nom' => 'Tata Province'],
            ['nom' => 'Ouezzane Province'],
            ['nom' => 'Ouezzane Province'],
            ['nom' => 'Mdiq-Fnideq'],
            ['nom' => 'Mdiq-Fnideq'],
            ['nom' => 'Sidi Kacem Province'],
            ['nom' => 'Sidi Kacem Province'],
            ['nom' => 'Youssoufia Province'],
            ['nom' => 'Youssoufia Province'],
            ['nom' => 'Sidi Slimane Province'],
            ['nom' => 'Sidi Slimane Province'],
            ['nom' => 'Tan-Tan Province'],
            ['nom' => 'Tan-Tan Province'],
            ['nom' => 'Taza Province'],
            ['nom' => 'Taza Province'],
            ['nom' => 'Tétouan Province'],
            ['nom' => 'Tétouan Province'],
            ['nom' => 'Tinghir Province'],
            ['nom' => 'Tinghir Province'],
            ['nom' => 'Youssoufia Province'],
            ['nom' => 'Youssoufia Province'],
            ['nom' => 'Oujda-Angad Province'],
            ['nom' => 'Oujda-Angad Province'],
            ['nom' => 'Errachidia Province'],
            ['nom' => 'Errachidia Province'],
            ['nom' => 'Figuig Province'],
            ['nom' => 'Figuig Province'],
            ['nom' => 'Khémisset Province'],
            ['nom' => 'Khémisset Province'],
            ['nom' => 'Taourirt Province'],
            ['nom' => 'Taourirt Province'],
            ['nom' => 'Taroudannt Province'],
            ['nom' => 'Taroudannt Province'],
            ['nom' => 'Tata Province'],
            ['nom' => 'Tata Province'],
            ['nom' => 'Al Hoceïma Province'],
            ['nom' => 'Al Hoceïma Province'],
            ['nom' => 'Ouarzazate Province'],
            ['nom' => 'Ouarzazate Province'],
            ['nom' => 'Essaouira Province'],
            ['nom' => 'Essaouira Province'],
            ['nom' => 'Ouezzane Province'],
            ['nom' => 'Ouezzane Province'],
            ['nom' => 'Sidi Bennour Province'],
            ['nom' => 'Sidi Bennour Province'],
            ['nom' => 'Settat Province'],
            ['nom' => 'Settat Province'],
            ['nom' => 'Chichaoua Province'],
            ['nom' => 'Chichaoua Province'],
            ['nom' => 'Ben Slimane Province'],
            ['nom' => 'Ben Slimane Province'],
            ['nom' => 'Berrechid Province'],
            ['nom' => 'Berrechid Province'],
            ['nom' => 'Casablanca Province'],
            ['nom' => 'Casablanca Province'],
            ['nom' => 'El Jadida Province'],
            ['nom' => 'El Jadida Province'],
            ['nom' => 'Fahs-Anjra'],
            ['nom' => 'Fahs-Anjra'],
            ['nom' => 'Fès-Meknès'],
            ['nom' => 'Fès-Meknès'],
            ['nom' => 'Guelmim-Oued Noun'],
            ['nom' => 'Guelmim-Oued Noun'],
            ['nom' => 'Kénitra Province'],
            ['nom' => 'Kénitra Province'],
            ['nom' => 'Khouribga Province'],
            ['nom' => 'Khouribga Province'],
            ['nom' => 'Laâyoune Province'],
            ['nom' => 'Laâyoune Province'],
            ['nom' => 'Marrakech-Safi'],
            ['nom' => 'Marrakech-Safi'],
            ['nom' => 'Oriental'],
            ['nom' => 'Oriental'],
            ['nom' => 'Rabat-Salé-Kénitra'],
            ['nom' => 'Rabat-Salé-Kénitra'],
            ['nom' => 'Souss-Massa'],
            ['nom' => 'Souss-Massa'],
            ['nom' => 'Tanger-Tétouan-Al Hoceïma'],
            ['nom' => 'Tanger-Tétouan-Al Hoceïma'],
            ['nom' => 'Drâa-Tafilalet'],
            ['nom' => 'Drâa-Tafilalet'],
            ['nom' => 'Guelmim-Oued Noun'],
            ['nom' => 'Guelmim-Oued Noun'],
            ['nom' => 'Laâyoune-Sakia El Hamra'],
            ['nom' => 'Laâyoune-Sakia El Hamra'],
            ['nom' => 'Dakhla-Oued Ed-Dahab'],
            ['nom' => 'Dakhla-Oued Ed-Dahab'],
        ];

        foreach ($villeData as $data) {
            $cityExists = Ville::where('nom', $data['nom'])->exists();
            if (!$cityExists) {
                Ville::create($data);
            }
        }
    }
}
